'''
    'Sample' : { 'Weight': 10, 'Cost' : 1, 'Type' : ['B','S','P','LA','MA','HA','2','1','Si','Ma','Ex','Ra','Ar',], },
B, S, P          - Blunt, Slash, Pierce
LA, MA, HA        - Light Armor, Medium Armor, Heavy Armor
2, 1                - 2 Handed, 1 Handed
Si, Ma, Ex, Ra, Ar  - Simple, Martial, Exotic, Ranged (bows), Ranged (arrows)s
    If you want to make your life hell:
https://the-eye.eu/public/Books/rpg.rem.uz/Pathfinder/3rd%20Party/Rite%20Publishing/101%20Series/101%20Special%20Materials%20%26%20Power%20Components.pdf
'''
common_material = {
    'Bronze': {
        'Weight': 1,
        'AC': 8,
        'Cost': .8,
        'Type': [
            'B',
            'S',
            'P',
            'MA',
            'HA',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Copper': {
        'Weight': 1,
        'AC': 6,
        'Cost': .8,
        'Type': [
            'B',
            'S',
            'P',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Iron': {
        'Weight': 1,
        'AC': 10,
        'Cost': 1,
        'Type': [
            'B',
            'S',
            'P',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Lead': {
        'Weight': 1.5,
        'AC': 8,
        'Cost': 1.1,
        'Type': [
            'B',
            'S',
            'P',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Steel': {
        'Weight': 1,
        'AC': 10,
        'Cost': 1,
        'Type': [
            'B',
            'S',
            'P',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Oak': {
        'Weight': .5,
        'AC': 2,
        'Cost': .25,
        'Type': [
            'B',
            'P',
            'LA',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ra',
        ],
    },
    'Yew': {
        'Weight': .5,
        'AC': 2,
        'Cost': .25,
        'Type': [
            'B',
            'P',
            'LA',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ra',
        ],
    },
    'Hide': {
        'Weight': .5,
        'AC': 8,
        'Cost': .8,
        'Type': [
            'LA',
            'MA',
        ],
    },
    'Leather': {
        'Weight': .5,
        'AC': 8,
        'Cost': .8,
        'Type': [
            'LA',
            'MA',
        ],
    },
}
uncommon_material = {
    'Adamantine': {
        'Weight': 1,
        'AC': 20,
        'Cost': 1.8,
        'Type': [
            'B',
            'S',
            'P',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Bone': {
        'Weight': 1,
        'AC': 6,
        'Cost': .8,
        'Type': [
            'B',
            'S',
            'LA',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Darkwood': {
        'Weight': .2,
        'AC': 5,
        'Cost': 1.05,
        'Type': [
            'B',
            'P',
            'LA',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ra',
        ],
    },
    'Dragonskin': {
        'Weight': 1,
        'AC': 12,
        'Cost': 2.25,
        'Type': ['LA', 'MA', 'HA'],
    },
    'Dragonhide': {
        'Weight': 1,
        'AC': 10,
        'Cost': 2.5,
        'Type': [
            'LA',
            'MA',
            'HA',
        ],
    },
    'Gold': {
        'Weight': 1,
        'AC': 5,
        'Cost': 10,
        'Type': [
            'S',
            'P',
            'MA',
            '1',
            'Si',
            'Ex',
            'Ra',
            'Ar',
        ],
    },
    'Greenwood': {
        'Weight': .5,
        'AC': 2,
        'Cost': 1.15,
        'Type': [
            'B',
            'P',
            'LA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ra',
        ],
    },
    'Platinum': {
        'Weight': .7,
        'AC': 15,
        'Cost': 5,
        'Type': [
            'S',
            'P',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Silkweave': {
        'Weight': .15,
        'AC': 10,
        'Cost': 2,
        'Type': [
            'LA',
        ],
    },
    'Silver': {
        'Weight': 1,
        'AC': 8,
        'Cost': 1.15,
        'Type': [
            'S',
            'P',
            'MA',
            '1',
            'Si',
            'Ex',
            'Ra',
            'Ar',
        ],
    },
    'Stone': {
        'Weight': .75,
        'AC': 2,
        'Cost': .25,
        'Type': [
            'B',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
}
rare_material = {
    'Angelskin': {
        'Weight': .2,
        'AC': 5,
        'Cost': 2.75,
        'Type': [
            'LA',
            'MA',
        ],
    },
    'Cold Iron': {
        'Weight': 1,
        'AC': 10,
        'Cost': 2,
        'Type': [
            'S',
            'P',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Dreamstone': {
        'Weight': .5,
        'AC': 10,
        'Cost': 2.25,
        'Type': [
            'B',
            'P',
            'LA',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Elysian Bronze': {
        'Weight': 1,
        'AC': 10,
        'Cost': 2,
        'Type': [
            'B',
            'S',
            'P',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Griffon Mane': {
        'Weight': .2,
        'AC': 1,
        'Cost': 2,
        'Type': [
            'LA',
            'MA',
            'HA',
        ],
    },
    'Ironwood': {
        'Weight': .7,
        'AC': 10,
        'Cost': 1.8,
        'Type': [
            'B',
            'P',
            'LA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ra',
        ],
    },
    'Obsidian': {
        'Weight': .75,
        'AC': 5,
        'Cost': 1.5,
        'Type': [
            'S',
            'P',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Viridium': {
        'Weight': 1,
        'AC': 10,
        'Cost': 1.5,
        'Type': [
            'S',
            'P',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
}
very_rare_material = {
    'Blood Crystal': {
        'Weight': 1,
        'AC': 10,
        'Cost': 2.75,
        'Type': [
            'S',
            'P',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Darkleaf Cloth': {
        'Weight': .2,
        'AC': 10,
        'Cost': 2.75,
        'Type': [
            'LA',
        ],
    },
    'Mithral': {
        'Weight':
        .5,
        'AC':
        15,
        'Cost':
        3,
        'Type': [
            'B',
            'S',
            'P',
            'LA',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Hot Siccatite': {
        'Weight':
        .8,
        'AC':
        10,
        'Cost':
        3,
        'Type': [
            'B',
            'S',
            'P',
            'LA',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Cold Siccatite': {
        'Weight':
        .8,
        'AC':
        10,
        'Cost':
        3,
        'Type': [
            'B',
            'S',
            'P',
            'LA',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Wyroot': {
        'Weight': 1.5,
        'AC': 5,
        'Cost': 2.5,
        'Type': [
            'B',
            'P',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ra',
        ],
    },
}
legendary_material = {
    'Horacalcum': {
        'Weight': 1,
        'AC': 15,
        'Cost': 5,
        'Type': [
            'B',
            'S',
            'P',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Mindglass': {
        'Weight': 1,
        'AC': 10,
        'Cost': 4,
        'Type': [
            'B',
            'S',
            'P',
            'LA',
            'MA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Noqual': {
        'Weight':
        .5,
        'AC':
        10,
        'Cost':
        3,
        'Type': [
            'B',
            'S',
            'P',
            'LA',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Umbrite': {
        'Weight':
        1,
        'AC':
        18,
        'Cost':
        3,
        'Type': [
            'B',
            'S',
            'P',
            'LA',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Voidglass': {
        'Weight': .5,
        'AC': 10,
        'Cost': 3.25,
        'Type': [
            'S',
            'P',
            'LA',
            'MA',
            'HA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ar',
        ],
    },
    'Whipwood': {
        'Weight': .2,
        'AC': 9,
        'Cost': 3,
        'Type': [
            'B',
            'P',
            'LA',
            '2',
            '1',
            'Si',
            'Ma',
            'Ex',
            'Ra',
        ],
    },
}
"""
https://the-eye.eu/public/Books/rpg.rem.uz/Pathfinder/Roleplaying%20Game/PZO1114%20GameMastery%20Guide%20%283rd%20printing%29.pdf
Level 0 : 12.5 GP
Level 1 : 25 GP
Level 2 : 150 GP
Level 3 : 375 GP
Level 4 : 700 GP
Level 5 : 1125 GP
Level 6 : 1650 GP
Level 7 : 2275 GP
Level 8 : 3000 GP
Level 9 : 4825 GP
"""
level_0 = [
    'Acid Splash',
    'Arcane Mark',
    'Bleed',
    'Create Water',
    'Dancing Lights',
    'Daze',
    'Detect Magic',
    'Detect Poison',
    'Disrupt Undead',
    'Flare',
    'Ghost Sound',
    'Guidance',
    'Know Direction',
    'Light',
    'Lullaby',
    'Mage Hand',
    'Mending',
    'Message',
    'Open/Close',
    'Prestidigitation',
    'Purify Food and Drink',
    'Ray of Frost',
    'Read Magic',
    'Resistance',
    'Stabilize',
    'Summon Instrument',
    'Touch of Fatigue',
    'Virtue',
    'Brand',
    'Putrefy Food and Drink',
    'Sift',
    'Spark',
    'Unwitting Ally',
    'Haunted Fey Aspect',
]
level_1 = [
    'Alarm', 'Animal Messenger', 'Animate Rope', 'Bane', 'Bless',
    'Bless Water', 'Bless Weapon', 'Burning Hands', 'Calm Animals',
    'Cause Fear', 'Charm Animal', 'Charm Person', 'Chill Touch', 'Color Spray',
    'Command', 'Comprehend Languages', 'Confusion, Lesser',
    'Cure Light Wounds', 'Curse Water', 'Deathwatch', 'Delay Poison',
    'Detect Animals or Plants', 'Detect Chaos', 'Detect Evil', 'Detect Good',
    'Detect Law', 'Detect Secret Doors', 'Detect Snares and Pits',
    'Detect Undead', 'Disguise Self', 'Divine Favor', 'Doom',
    'Endure Elements', 'Enlarge Person', 'Entangle', 'Entropic Shield',
    'Erase', 'Expeditious Retreat', 'Faerie Fire', 'Feather Fall',
    'Floating Disk', 'Goodberry', 'Grease', 'Hide from Animals',
    'Hide from Undead', 'Hideous Laughter', 'Hold Portal', 'Hypnotism',
    'Identify', 'Inflict Light Wounds', 'Jump', 'Longstrider', 'Mage Armor',
    'Magic Aura', 'Magic Fang', 'Magic Missile', 'Magic Mouth', 'Magic Stone',
    'Magic Weapon', 'Mount', 'Obscure Object', 'Obscuring Mist',
    'Pass without Trace', 'Produce Flame', 'Protection from Chaos',
    'Protection from Evil', 'Protection from Good', 'Protection from Law',
    'Ray of Enfeeblement', 'Reduce Person', 'Remove Fear', 'Resist Energy',
    'Restoration, Lesser', 'Sanctuary', 'Shield', 'Shield of Faith',
    'Shillelagh', 'Shocking Grasp', 'Silent Image', 'Sleep',
    'Speak with Animals', 'Summon Monster I', "Summon Nature's Ally I",
    'True Strike', 'Undetectable Alignment', 'Unseen Servant', 'Ventriloquism',
    'Alter Winds', 'Ant Haul', 'Aspect of the Falcon', 'Beguiling Gift',
    "Bomber's Eye", 'Borrow Skill', 'Break', 'Bristle', 'Burst Bonds',
    'Call Animal', 'Challenge Evil', 'Cloak of Shade', "Crafter's Curse",
    "Crafter's Fortune", 'Dancing Lantern', 'Detect Aberration',
    'Expeditious Excavation', 'Feather Step', 'Flare Burst', 'Ghostbane Dirge',
    'Glide', 'Grace', 'Gravity Bow', "Hero's Defiance", 'Honeyed Tongue',
    "Hunter's Howl", 'Hydraulic Push', 'Ill Omen', 'Innocence', 'Invigorate',
    'Keen Senses', "Knight's Calling", 'Lead Blades', 'Mask Dweomer',
    'Memory Lapse', 'Negate Aroma', 'Rally Point',
    'Rejuvenate Eidolon, Lesser', 'Residual Tracking', 'Restful Sleep',
    'Saving Finale', 'Sculpt Corpse', 'Share Language', 'Solid Note',
    'Stone Fist', 'Stumble Gap', 'Timely Inspiration', 'Tireless Pursuit',
    'Touch of Gracelessness', 'Touch of the Sea', 'Unfetter', 'Vanish',
    'Veil of Positive Energy', 'Wrath', 'Abundant Ammunition', 'Adjuring Step',
    'Adoration', 'Air Bubble', 'Bowstaff', 'Compel Hostility', 'Damp Powder',
    "Deadeye's Lore", 'Fabricate Bullets', 'Illusion of Calm', 'Jury-Rig',
    'Liberating Command', 'Life Conduit', 'Litany of Sloth',
    'Litany of Weakness', 'Lock Gaze', 'Longshot', 'Mirror Strike',
    'Moment of Greatness', 'Negative Reaction', 'Peacebond',
    'Reinforce Armaments', 'Returning Weapon', 'See Alignment', 'Shock Shield',
    'Sun Metal', 'Tactical Acumen', 'Targeted Bomb Admixture',
    'Unerring Weapon', 'Warding Weapon', 'Weaken Powder'
]
level_2 = [
    'Acid Arrow', 'Aid', 'Align Weapon', 'Alter Self', 'Animal Trance',
    'Arcane Lock', 'Augury', 'Barkskin', "Bear's Endurance",
    'Blindness/Deafness', 'Blur', "Bull's Strength", 'Calm Emotions',
    "Cat's Grace", 'Chill Metal', 'Command Undead', 'Consecrate',
    'Continual Flame', 'Cure Moderate Wounds', 'Darkness', 'Darkvision',
    'Daze Monster', 'Death Knell', 'Desecrate', 'Detect Thoughts',
    "Eagle's Splendor", 'Enthrall', 'False Life', 'Find Traps', 'Fire Trap',
    'Flame Blade', 'Flaming Sphere', 'Fog Cloud', "Fox's Cunning",
    'Gentle Repose', 'Ghoul Touch', 'Glitterdust', 'Gust of Wind',
    'Heat Metal', 'Heroism', 'Hold Animal', 'Hold Person', 'Hypnotic Pattern',
    'Inflict Moderate Wounds', 'Invisibility', 'Knock', 'Levitate',
    'Locate Object', 'Make Whole', 'Minor Image', 'Mirror Image',
    'Misdirection', "Owl's Wisdom", 'Phantom Trap', 'Protection from Arrows',
    'Protection from Energy', 'Pyrotechnics', 'Rage', 'Reduce Animal',
    'Remove Paralysis', 'Rope Trick', 'Scare', 'Scorching Ray',
    'See Invisibility', 'Shatter', 'Shield Other', 'Silence', 'Snare',
    'Soften Earth and Stone', 'Sound Burst', 'Speak with Plants',
    'Spectral Hand', 'Spider Climb', 'Spike Growth', 'Spiritual Weapon',
    'Status', 'Suggestion', 'Summon Monster II', "Summon Nature's Ally II",
    'Summon Swarm', 'Tongues', 'Touch of Idiocy', 'Tree Shape', 'Warp Wood',
    'Web', 'Whispering Wind', 'Wind Wall', 'Wood Shape', 'Zone of Truth',
    'Accelerate Poison', 'Alchemical Allocation', 'Allfood', 'Arrow Eruption',
    'Aspect of the Bear', 'Aura of Greater Courage', 'Bestow Grace',
    'Blessing of Courage and Life', 'Blood Biography', 'Bloodhound',
    'Burning Gaze', 'Cacophonous Call', 'Campfire Wall', 'Castigate',
    'Chameleon Stride', 'Confess', 'Corruption Resistance', 'Create Pit',
    'Create Treasure Map', 'Dust of Twilight', 'Eagle Eye', 'Elemental Speech',
    'Elemental Touch', 'Enter Image', 'Evolution Surge, Lesser',
    'Feast of Ashes', 'Fester', 'Fire Breath', 'Fire of Entanglement',
    'Flames of the Faithful', 'Follow Aura', 'Gallant Inspiration',
    'Guiding Star', 'Hidden Speech', 'Hide Campsite', "Hunter's Eye",
    'Instant Armor', 'Light Lance', 'Lockjaw', 'Natural Rhythm',
    "Oracle's Burden", "Paladin's Sacrifice", 'Perceive Cues', 'Pox Pustules',
    'Protective Spirit', 'Righteous Vigor', 'Sacred Bond', 'Saddle Surge',
    'Scent Trail', 'Slipstream', 'Stone Call', 'Summon Eidolon',
    'Transmute Potion to Poison', 'Versatile Weapon', 'Vomit Swarm',
    'Wake of Light', 'Weapon of Awe', 'Ablative Barrier', 'Animal Aspect',
    'Ant Haul, Communal', 'Bestow Weapon Proficiency', 'Blistering Invective',
    'Brow Gasher', 'Bullet Shield', 'Certain Grip', 'Destabilize Powder',
    'Discovery Torch', 'Divine Arrow', 'Effortless Armor',
    'Endure Elements, Communal', 'Fiery Shuriken', 'Forest Friend',
    'Frost Fall', 'Instrument of Agony', 'Kinetic Reverberation',
    'Litany of Defense', 'Litany of Eloquence', 'Litany of Entanglement',
    'Litany of Righteousness', 'Litany of Warding', 'Locate Weakness',
    'Magic Siege Engine', 'Mask Dweomer, Communal', 'Mount, Communal',
    'Pilfering Hand', 'Protection from Chaos, Communal',
    'Protection from Evil, Communal', 'Protection from Good, Communal',
    'Protection from Law, Communal', 'Qualm', 'Recoil Fire',
    'Reinforce Armaments, Communal', 'Reloading Hands',
    'Returning Weapon, Communal', 'Ricochet Shot', 'Shadow Bomb Admixture',
    'Share Language, Communal', 'Spontaneous Immolation', 'Stabilize Powder',
    'Telekinetic Assembly', 'Thunder Fire', 'Touch Injection', 'Twisted Space',
    'Wilderness Soldiers'
]
level_3 = [
    'Animate Dead', 'Arcane Sight', 'Beast Shape I', 'Bestow Curse', 'Blink',
    'Call Lightning', 'Charm Monster', 'Clairaudience/Clairvoyance',
    'Command Plants', 'Confusion', 'Contagion', 'Create Food and Water',
    'Crushing Despair', 'Cure Serious Wounds', 'Daylight', 'Deeper Darkness',
    'Deep Slumber', 'Diminish Plants', 'Discern Lies', 'Dispel Magic',
    'Displacement', 'Dominate Animal', 'Explosive Runes', 'Fear', 'Fireball',
    'Flame Arrow', 'Fly', 'Gaseous Form', 'Geas, Lesser', 'Glibness',
    'Glyph of Warding', 'Good Hope', 'Halt Undead', 'Haste', 'Heal Mount',
    'Helping Hand', 'Illusory Script', 'Inflict Serious Wounds',
    'Invisibility Purge', 'Invisibility Sphere', 'Keen Edge', 'Lightning Bolt',
    'Magic Circle against Chaos', 'Magic Circle against Evil',
    'Magic Circle against Good', 'Magic Circle against Law',
    'Magic Fang, Greater', 'Magic Vestment', 'Magic Weapon, Greater',
    'Major Image', 'Meld into Stone', 'Neutralize Poison', 'Nondetection',
    'Phantom Steed', 'Plant Growth', 'Poison', 'Prayer', 'Quench',
    'Ray of Exhaustion', 'Remove Blindness/Deafness', 'Remove Curse',
    'Remove Disease', 'Repel Vermin', 'Scrying', 'Sculpt Sound',
    'Searing Light', 'Secret Page', 'Sepia Snake Sigil', 'Shrink Item',
    'Sleet Storm', 'Slow', 'Speak with Dead', 'Stinking Cloud', 'Stone Shape',
    'Summon Monster III', "Summon Nature's Ally III", 'Tiny Hut',
    'Vampiric touch', 'Water Breathing', 'Water Walk', 'Absorbing Touch',
    'Amplify Elixir', 'Aqueous Orb', 'Arcane Concordance',
    'Aspect of the Stag', 'Banish Seeming', 'Bloody Claws', 'Borrow Fortune',
    'Cast Out', 'Cloak of Winds', 'Coordinated Effort', 'Cup of Dust',
    'Defile Armor', 'Devolution', 'Divine Transfer', 'Draconic Reservoir',
    'Elemental Aura', 'Evolution Surge', 'Feather Step, Mass',
    'Fire of Judgment', 'Ghostbane Dirge, Mass', 'Holy Whisper',
    'Hydraulic Torrent', 'Instant Enemy', 'Invigorate, Mass', "Jester's Jaunt",
    'Life Bubble', 'Lily Pad Stride', 'Marks Of Forbiddance', 'Nap Stack',
    "Nature's Exile", 'Pain Strike', 'Purging Finale', 'Rejuvenate Eidolon',
    'Retribution', 'Reviving Finale', 'Sanctify Armor', 'Screech',
    'Seek Thoughts', 'Share Senses', 'Shifting Sand', 'Spiked Pit',
    'Strong Jaw', 'Thorn Body', 'Thundering Drums', 'Tireless Pursuers',
    'Twilight Knife', 'Venomous Bolt', 'Ward the Faithful', 'Wrathful Mantle',
    'Absorb Toxicity', 'Animal Aspect, Greater', 'Burst of Speed',
    'Chain of Perdition', 'Companion Mind Link', 'Darkvision, Communal',
    'Daybreak Arrow', 'Deadly Juggernaut', 'Delay Poison, Communal',
    'Flash Fire', 'Healing Thief', 'Hostile Levitation',
    'Life Conduit, Improved', 'Lightning Lash Bomb Admixture',
    'Litany of Escape', 'Litany of Sight', 'Named Bullet', 'Obsidian Flow',
    'Pellet Blast', 'Phantom Chariot', 'Phantom Driver',
    'Phantom Steed, Communal', 'Protection from Arrows, Communal',
    'Protection from Energy, Communal', 'Pup Shape', 'Resinous Skin',
    'Resist Energy, Communal', 'Spider Climb, Communal', 'Tongues, Communal'
]
level_4 = [
    'Air Walk', 'Animal Growth', 'Antiplant Shell', 'Arcane Eye',
    'Beast Shape II', 'Black Tentacles', 'Blight', 'Break Enchantment',
    'Chaos Hammer', 'Commune with Nature', 'Control Water',
    'Cure Critical Wounds', 'Death Ward', 'Detect Scrying',
    'Dimensional Anchor', 'Dimension Door', 'Dismissal', 'Dispel Chaos',
    'Dispel Evil', 'Divination', 'Divine Power', 'Dominate Person',
    'Elemental Body I', 'Enervation', 'Enlarge Person, Mass', 'Fire Shield',
    'Flame Strike', 'Freedom of Movement', 'Giant Vermin',
    'Globe of Invulnerability, Lesser', 'Hallucinatory Terrain',
    'Hold Monster', 'Holy Smite', 'Holy Sword', 'Ice Storm', 'Illusory Wall',
    'Imbue with Spell Ability', 'Inflict Critical Wounds',
    'Invisibility, Greater', 'Legend Lore', 'Locate Creature',
    'Mark of Justice', 'Minor Creation', 'Mnemonic Enhancer', 'Modify Memory',
    "Order's Wrath", 'Phantasmal Killer', 'Planar Ally, Lesser',
    'Rainbow Pattern', 'Reduce Person, Mass', 'Reincarnate',
    'Resilient Sphere', 'Restoration', 'Rusting Grasp', 'Secure Shelter',
    'Sending', 'Shadow Conjuration', 'Shout', 'Solid Fog', 'Spell Immunity',
    'Spike Stones', 'Stoneskin', 'Summon Monster IV',
    "Summon Nature's Ally IV", 'Tree Stride', 'Unholy Blight', 'Wall of Fire',
    'Wall of Ice', 'Zone of Silence', 'Acid Pit', 'Aspect of the Wolf',
    'Ball Lightning', 'Blaze of Glory', 'Blessing of Fervor',
    'Blessing of the Salamander', 'Bow Spirit', 'Brand, Greater',
    'Calcific Touch', "Coward's Lament", 'Denounce', 'Detonate',
    'Discordant Blast', "Dragon's Breath", 'Evolution Surge, Greater',
    'Firefall', 'Fire of Vengeance', 'Fluid Form', 'Forced Repentance',
    'Geyser', 'Grove of Respite', 'Heroic Finale', "King's Castle",
    'Moonstruck', 'Oath of Peace', 'Planar Adaptation', 'Purified Calling',
    'Rebuke', 'Resounding Blow', 'Rest Eternal', 'River of Wind',
    'Sacrificial Oath', 'Shadow Projection', 'Shared Wrath', 'Sleepwalk',
    'Spiritual Ally', 'Spite', 'Stay the Hand', 'Threefold Aspect',
    'Transmogrify', 'Treasure Stitching', 'True Form', 'Universal Formula',
    'Wandering Star Motes', 'Air Walk, Communal', 'Debilitating Portent',
    'Find Quarry', 'Hostile Juxtaposition', 'Judgment Light',
    'Litany of Madness', 'Litany of Thunder', 'Litany of Vengeance',
    'Magic Siege Engine, Greater', 'Mutagenic Touch', 'Named Bullet, Greater',
    'Nondetection, Communal', 'Shocking Image', 'Stoneskin, Communal',
    'Summoner Conduit', 'Telekinetic Charge', 'Terrain Bond',
    'Viper Bomb Admixture', 'Water Walk, Communal', 'Wreath of Blades'
]
level_5 = [
    'Atonement', 'Awaken', 'Baleful Polymorph', 'Beast Shape III',
    'Breath of Life', 'Call Lightning Storm', 'Cloudkill', 'Command, Greater',
    'Commune', 'Cone of Cold', 'Contact Other Plane', 'Control Winds',
    'Cure Light Wounds, Mass', 'Dispel Good', 'Dispel Law',
    'Dispel Magic, Greater', 'Disrupting Weapon', 'Dream', 'Elemental Body II',
    'Fabricate', 'False Vision', 'Feeblemind', 'Hallow', 'Heroism, Greater',
    'Inflict Light Wounds, Mass', 'Insect Plague', 'Interposing Hand',
    "Mage's Faithful Hound", "Mage's Private Sanctum", 'Magic Jar',
    'Major Creation', 'Mind Fog', 'Mirage Arcana', 'Mislead', 'Nightmare',
    'Overland Flight', 'Passwall', 'Permanency', 'Persistent Image',
    'Planar Binding, Lesser', 'Plane Shift', 'Plant Shape I', 'Polymorph',
    'Prying Eyes', 'Raise Dead', 'Righteous Might', 'Secret Chest', 'Seeming',
    'Shadow Evocation', 'Shadow Walk', 'Slay Living', 'Song of Discord',
    'Spell Resistance', 'Suggestion, Mass', 'Summon Monster V',
    "Summon Nature's Ally V", 'Symbol of Pain', 'Symbol of Sleep',
    'Telekinesis', 'Telepathic Bond', 'Teleport', 'Transmute Mud to Rock',
    'Transmute Rock to Mud', 'True Seeing', 'Unhallow', 'Wall of Force',
    'Wall of Stone', 'Wall of Thorns', 'Waves of Fatigue', "Bard's Escape",
    'Cacophonous Call, Mass', 'Castigate, Mass', 'Cleanse', 'Cloak of Dreams',
    'Deafening Song Bolt', 'Delayed Consumption', 'Elude Time', 'Fire Snake',
    'Foe to Friend', 'Frozen Note', 'Hungry Pit', 'Pain Strike, Mass',
    'Phantasmal Web', 'Pillar of Life', 'Rejuvenate Eidolon, Greater',
    'Resurgent Transformation', 'Snake Staff', 'Stunning Finale',
    'Suffocation', 'Unwilling Shield', 'Dust Form', 'Energy Siege Shot',
    'Languid Bomb Admixture', 'Life Conduit, Greater',
    'Spell Immunity, Communal', 'Symbol of Striking', 'Tar Pool'
]
level_6 = [
    'Acid Fog', 'Analyze Dweomer', 'Animate Objects', 'Antilife Shell',
    'Antimagic Field', 'Banishment', "Bear's Endurance, Mass",
    'Beast Shape IV', 'Blade Barrier', "Bull's Strength, Mass",
    "Cat's Grace, Mass", 'Chain Lightning', 'Charm Monster, Mass',
    'Circle of Death', 'Contingency', 'Create Undead',
    'Cure Moderate Wounds, Mass', 'Disintegrate', "Eagle's Splendor, Mass",
    'Elemental Body III', 'Eyebite', 'Find the Path', 'Fire Seeds',
    'Flesh to Stone', 'Forbiddance', 'Forceful Hand', 'Form of the Dragon I',
    "Fox's Cunning, Mass", 'Freezing Sphere', 'Geas/Quest',
    'Globe of Invulnerability', 'Glyph of Warding, Greater',
    'Guards and Wards', 'Harm', 'Heal', "Heroes' Feast",
    'Inflict Moderate Wounds, Mass', 'Ironwood', 'Irresistible Dance',
    'Liveoak', "Mage's Lucubration", 'Move Earth', "Owl's Wisdom, Mass",
    'Permanent Image', 'Planar Ally', 'Planar Binding', 'Plant Shape II',
    'Programmed Image', 'Project Image', 'Repel Wood', 'Repulsion',
    'Scrying, Greater', 'Shout, Greater', 'Spellstaff', 'Stone Tell',
    'Stone to Flesh', 'Summon Monster VI', "Summon Nature's Ally VI",
    'Symbol of Fear', 'Symbol of Persuasion', 'Sympathetic Vibration',
    'Transformation', 'Transport via Plants', 'Undeath to Death', 'Veil',
    'Wall of Iron', 'Wind Walk', 'Word of Recall', 'Brilliant Inspiration',
    'Contagious Flame', 'Deadly Finale', 'Enemy Hammer',
    'Euphoric Tranquility', 'Fester, Mass', "Fool's Forbiddance", 'Getaway',
    'Pied Piping', 'Planar Adaptation, Mass', 'Sirocco', 'Swarm Skin',
    'Twin Form', 'Caging Bomb Admixture', 'Energy Siege Shot, Greater',
    'Hostile Juxtaposition, Greater', 'Walk through Space'
]
level_7 = [
    'Animate Plants', 'Arcane Sight, Greater', 'Blasphemy', 'Changestaff',
    'Control Undead', 'Control Weather', 'Creeping Doom',
    'Cure Serious Wounds, Mass', 'Delayed Blast Fireball', 'Destruction',
    'Dictum', 'Elemental Body IV', 'Ethereal Jaunt', 'Finger of Death',
    'Fire Storm', 'Forcecage', 'Form of the Dragon II', 'Giant Form I',
    'Grasping Hand', 'Hold Person, Mass', 'Holy Word',
    'Inflict Serious Wounds, Mass', 'Insanity', 'Instant Summons',
    'Invisibility, Mass', 'Limited Wish', "Mage's Magnificent Mansion",
    "Mage's Sword", 'Phase Door', 'Plant Shape III', 'Polymorph, Greater',
    'Power Word Blind', 'Prismatic Spray', 'Refuge', 'Regenerate',
    'Restoration, Greater', 'Resurrection', 'Reverse Gravity', 'Sequester',
    'Shadow Conjuration, Greater', 'Simulacrum', 'Spell Turning', 'Statue',
    'Summon Monster VII', "Summon Nature's Ally VII", 'Sunbeam',
    'Symbol of Stunning', 'Symbol of Weakness', 'Teleport, Greater',
    'Teleport Object', 'Transmute Metal to Wood', 'Vision',
    'Waves of Exhaustion', 'Word of Chaos', 'Deflection', 'Expend',
    'Firebrand', 'Fly, Mass', 'Phantasmal Revenge', 'Rampart', 'Vortex',
    'Arcane Cannon', 'Jolting Portent', 'Siege of Trees'
]
level_8 = [
    'Animal Shapes', 'Antipathy', 'Binding', 'Clenched Fist', 'Cloak of Chaos',
    'Clone', 'Control Plants', 'Create Greater Undead',
    'Cure Critical Wounds, Mass', 'Demand', 'Dimensional Lock',
    'Discern Location', 'Earthquake', 'Form of the Dragon III',
    'Giant Form II', 'Holy Aura', 'Horrid Wilting', 'Incendiary Cloud',
    'Inflict Critical Wounds, Mass', 'Iron Body', 'Maze', 'Mind Blank',
    'Moment of Prescience', 'Planar Ally, Greater', 'Planar Binding, Greater',
    'Polar Ray', 'Polymorph Any Object', 'Power Word Stun', 'Prismatic Wall',
    'Protection from Spells', 'Prying Eyes, Greater', 'Repel Metal or Stone',
    'Scintillating Pattern', 'Screen', 'Shadow Evocation, Greater',
    'Shield of Law', 'Spell Immunity, Greater', 'Summon Monster VIII',
    "Summon Nature's Ally VIII", 'Sunburst', 'Symbol of Death',
    'Symbol of Insanity', 'Sympathy', 'Telekinetic Sphere', 'Temporal Stasis',
    'Trap the Soul', 'Unholy Aura', 'Whirlwind', 'Divine Vessel', 'Seamantle',
    'Stormbolts', 'Wall of Lava', 'Frightful Aspect'
]
level_9 = [
    'Astral Projection', 'Crushing Hand', 'Dominate Monster',
    'Elemental Swarm', 'Energy Drain', 'Etherealness', 'Foresight', 'Freedom',
    'Gate', 'Heal, Mass', 'Hold Monster, Mass', 'Implosion', 'Imprisonment',
    "Mage's Disjunction", 'Meteor Swarm', 'Miracle', 'Power Word Kill',
    'Prismatic Sphere', 'Shades', 'Shambler', 'Shapechange', 'Soul Bind',
    'Storm of Vengeance', 'Summon Monster IX', "Summon Nature's Ally IX",
    'Teleportation Circle', 'Time Stop', 'True Resurrection',
    'Wail of the Banshee', 'Weird', 'Wish', 'Clashing Rocks', 'Fiery Body',
    'Suffocation, Mass', 'Tsunami', 'Wall of Suppression',
    'Winds of Vengeance', 'World Wave', 'Heroic Invocation',
    'Mind Blank, Communal', 'Siege of Trees, Greater',
    'Spell Immunity, Greater Communal'
]
level_likelihood = {
    0: 0.2597402597402597,
    1: 0.21038961038961038,
    2: 0.16623376623376623,
    3: 0.12727272727272726,
    4: 0.09350649350649351,
    5: 0.06493506493506493,
    6: 0.04155844155844156,
    7: 0.023376623376623377,
    8: 0.01038961038961039,
    9: 0.0025974025974025974,
}
odd_price = {
    'Magic Mouth': 1.0666666666666667,
    'Arcane Lock': 1.1666666666666667,
    'Continual Flame': 1.3333333333333333,
    'Phantom Trap': 1.3333333333333333,
    'Illusory Script': 1.1333333333333333,
    'Nondetection': 1.1333333333333333,
    'Sepia Snake Sigil': 2.3333333333333335,
    'Fire Trap': 1.0357142857142858,
    'Mnemonic Enhancer': 1.0714285714285714,
    'Stoneskin': 1.3571428571428572,
    'Animate Dead': 1.5,
    'False Vision': 1.2222222222222223,
    'Symbol of Pain': 1.8888888888888888,
    'Symbol of Sleep': 1.8888888888888888,
    'Create Undead': 1.0294117647058822,
    'Legend Lore': 1.1176470588235294,
    'True Seeing': 1.1176470588235294,
    'Circle of Death': 1.2647058823529411,
    'Undeath to Death': 1.2647058823529411,
    'Symbol of Fear': 1.5588235294117647,
    'Symbol of Persuasion': 3.911764705882353,
    'Project Image': 1.0021978021978022,
    'Vision': 1.10989010989011,
    'Forcecage': 1.2197802197802199,
    'Instant Summons': 1.4395604395604396,
    'Limited Wish': 1.6593406593406594,
    'Symbol of Stunning': 3.4175824175824174,
    'Symbol of Weakness': 3.4175824175824174,
    'Simulacrum': 3.857142857142857,
    'Create Greater Undead': 1.05,
    'Protection from Spells': 1.1666666666666667,
    'Sympathy': 1.5,
    'Symbol of Death': 2.6666666666666665,
    'Symbol of Insanity': 2.6666666666666665,
    'Temporal Stasis': 2.6666666666666665,
    'Trap the Soul': 7.666666666666667,
    'Refuge': 1.130718954248366,
    'Astral Projection': 1.261437908496732,
    'Teleportation Circle': 1.261437908496732,
    'Wish': 7.5359477124183005
}

die_values = {
    'Heavy Axe': [10, 12],
    'Light Axe': [8, 10],
    'Heavy Blade': [6, 8, 10],
    'Light Blade': [6, 8],
    'Close': [4, 6, 8],
    'Double': [4, 6, 8, 10],
    'Flail': [4, 6, 8],
    'Hammer': [4, 6, 8],
    'Monk': [4, 6, 8, 10],
    'Polearm': [6, 8, 10],
    'Spear': [6, 8],
    'Bows': [8, 10],
    'Crossbow': [6, 8],
    'Thrown': [4, 6],
}

possible_melee = {
    'Heavy Axe': [
        'bardiche',
        'battleaxe',
        'boarding axe',
        'dwarven waraxe',
        'greataxe',
        'heavy pick',
        'orc double axe',
        'tongi',
    ],
    'Light Axe': [
        'boarding axe',
        'butchering axe',
        'collapsible kumade',
        'gandasa',
        'handaxe',
        'hooked axe',
        'knuckle axe',
        'kumade',
        'light pick',
        'mattock',
        'throwing axe',
    ],
    'Heavy Blade': [
        'Ankus',
        'dueling sword',
        'bastard sword',
        'chakram',
        'double chicken saber',
        'double walking stick katana',
        'elven curve blade',
        'estoc',
        'falcata',
        'falchion',
        'flambard',
        'greatsword',
        'great terbutje',
        'katana',
        'khopesh',
        'klar',
        'longsword',
        'nine-ring broadsword',
        'nodachi',
        'scimitar',
        'scythe',
        'seven-branched sword',
        'shotel',
        'temple sword',
        'terbutje',
        'two-bladed sword',
    ],
    'Light Blade': [
        'bayonet',
        'butterfly knife',
        'butterfly sword',
        'chakram',
        'dagger',
        'deer horn knife',
        'Drow razor',
        'dueling dagger',
        'gladius',
        'hunga munga',
        'kama',
        'katar',
        'kerambit',
        'kukri',
        'machete',
        'madu',
        'manople',
        'pata',
        'quadrens',
        'rapier',
        'sanpkhang',
        'sawtooth sabre',
        'scizore',
        'shortsword',
        'sica',
        'sickle',
        'spiral rapier',
        'starknife',
        'swordbreaker dagger',
        'sword cane',
        'wakizashi',
        'war razor',
    ],
    'Close': [
        'bayonet',
        'brass knuckles',
        'cestus',
        'dan bong',
        'emei piercer',
        'fighting fan',
        'gauntlet',
        'iron brush',
        'katar',
        'klar',
        'madu',
        'mere club',
        'punching dagger',
        'rope gauntlet',
        'sap',
        'scizore',
        'spiked gauntlet',
        'tekko-kagi',
        'tonfa',
        'tri-bladed katar',
        'stake',
        'waveblade',
        'wushu dart',
    ],
    'Double': [
        'bo staff',
        'Boarding gaff',
        'chain-hammer',
        'chain spear',
        'dire flail',
        'double walking stick katana',
        'double-chained kama',
        'dwarven urgrosh',
        'gnome battle ladder',
        'gnome hooked hammer',
        'kusarigama',
        'monk\'s spade',
        'orc double axe',
        'quarterstaff',
        'taiaha',
        'two-bladed sword',
        'weighted spear',
    ],
    'Flail': [
        'battle poi',
        'bladed scarf',
        'Cat-o\'-nine-tails',
        'chain spear',
        'dire flail',
        'double chained kama',
        'dwarven dorn-dergar',
        'flail',
        'flying talon',
        'gnome pincher',
        'halfling rope-shot',
        'heavy flail',
        'kusarigama',
        'kyoketsu shoge',
        'meteor hammer',
        'morningstar',
        'nine-section whip',
        'nunchaku',
        'sansetsukon',
        'scorpion whip',
        'spiked chain',
        'urumi',
        'whip',
    ],
    'Hammer': [
        'aklys',
        'battle aspergillum',
        'Chain-hammer',
        'club',
        'gnome piston maul',
        'greatclub',
        'heavy mace',
        'lantern staff',
        'light hammer',
        'light mace',
        'mere club',
        'planson',
        'taiaha',
        'tetsubo',
        'wahaika',
        'warhammer',
    ],
    'Monk': [
        'bo staff',
        'brass knuckles',
        'butterfly sword',
        'cestus',
        'dan bong',
        'deer horn knife',
        'double chained kama',
        'double chicken saber',
        'emei piercer',
        'fighting fan',
        'hanbo',
        'jutte',
        'kama',
        'kusarigama',
        'kyoketsu shoge',
        'lungshuan tamo',
        'monk\'s spade',
        'nine-ring broadsword',
        'nine-section whip',
        'nunchaku',
        'quarterstaff',
        'rope dart',
        'sai',
        'sanpkhang',
        'sansetsukon',
        'seven-branched sword',
        'shang gou',
        'shuriken',
        'siangham',
        'temple sword',
        'tiger fork',
        'tonfa',
        'tri-point double-edged sword',
        'urumi',
        'wushu dart',
    ],
    'Polearm': [
        'bardiche',
        'bec de corbin',
        'bill',
        'Boarding gaff',
        'crook',
        'fauchard',
        'glaive',
        'glaive-guisarme',
        'gnome ripsaw glaive',
        'guisarme',
        'halberd',
        'hooked lance',
        'lucerne hammer',
        'mancatcher',
        'monk\'s spade',
        'naginata',
        'nodachi',
        'ranseur',
        'rhomphaia',
        'tepoztopilli',
        'tiger fork',
    ],
    'Spear': [
        'amentum',
        'boar spear',
        'chain spear',
        'elven branched spear',
        'javelin',
        'harpoon',
        'lance',
        'longspear',
        'orc skull ram',
        'pilum',
        'planson',
        'shortspear',
        'sibat',
        'spear',
        'stormshaft javelin',
        'tiger fork',
        'trident',
        'weighted spear',
    ],
}
possible_ranged = {
    'Bows': [
        'Composite longbow',
        'composite shortbow',
        'longbow',
        'hornbow',
        'composite hornbow',
        'shortbow',
    ],
    'Crossbow': [
        'double crossbow',
        'hand crossbow',
        'heavy crossbow',
        'launching crossbow',
        'light crossbow',
        'heavy repeating crossbow',
        'light repeating crossbow',
        'tube arrow shooter',
    ],
    'Thrown': [
        'aklys',
        'amentum',
        'atlatl',
        'blowgun',
        'bolas',
        'boomerang',
        'brutal bolas',
        'Chain-hammer',
        'chakram',
        'club',
        'dagger',
        'dart',
        'deer horn knife',
        'dueling dagger',
        'flask thrower',
        'halfling sling staff',
        'harpoon',
        'hunga munga',
        'javelin',
        'kestros',
        'light hammer',
        'pilum',
        'poisoned sand tube',
        'rope dart',
        'shortspear',
        'shuriken',
        'sibat',
        'sling',
        'sling glove',
        'spear',
        'starknife',
        'stormshaft javelin',
        'throwing axe',
        'trident',
        'wushu dart',
    ],
}

weapon_cost_and_weight = {
    'Heavy Axe': [19, 1.6],
    'Light Axe': [11, .9],
    'Heavy Blade': [12, 1.3],
    'Light Blade': [10, 1],
    'Close': [5, .5],
    'Double': [20, 1.1],
    'Flail': [14, 1.2],
    'Hammer': [22, 1.7],
    'Monk': [10, 1],
    'Polearm': [9, .8],
    'Spear': [13, 1.2],
    'Bows': [17, .4],
    'Crossbow': [29, 1.1],
    'Thrown': [7, .7],
}
